package com.jetsetslow.omniterm

import com.jetsetslow.omniterm.ui.ComposeServiceDraft
import com.jetsetslow.omniterm.ui.ComposeStackDraft
import com.jetsetslow.omniterm.ui.TopLevelNetworkDraft
import com.jetsetslow.omniterm.ui.TopLevelVolumeDraft
import com.jetsetslow.omniterm.ui.generateDockerComposeYaml
import java.io.File
import java.security.MessageDigest

/**
 * Deterministic source of the large-stack Compose fixture.
 *
 * The fixture is GENERATED, never hand-written, and generated by the app's own
 * [generateDockerComposeYaml] rather than by an independent YAML writer. That is not a shortcut: the
 * stress test asserts `renderComposeYaml(parse(text)) == text`, so the fixture has to already be in
 * exactly the form the renderer emits. Anything hand-authored drifts from the renderer the first
 * time its formatting changes, and the failure looks like a parser bug instead of a stale fixture.
 *
 * It is checked into the repository and mounted read-only into the disposable SSH fleet, so every
 * contributor exercises byte-identical input. [ComposeLargeStackFixtureTest] regenerates it and
 * fails on any drift, which is what makes "immutable" enforceable rather than a convention.
 */
object ComposeLargeStackFixture {

    const val SERVICE_COUNT = 400

    /** Path inside the disposable containers; see scripts/test-hosts/docker-compose.yml. */
    const val CONTAINER_PATH = "/fixtures/large-stack/compose.yml"

    /** Repository-relative location of the committed fixture. */
    const val REPO_PATH = "scripts/test-hosts/fixtures/large-stack/compose.yml"

    /** Zero-padded name of service [index], e.g. `service-000`. */
    fun serviceName(index: Int): String = "service-%03d".format(index)

    /**
     * Build the draft the fixture is rendered from. Every value is a pure function of [index] —
     * no clock, no UUID-derived content, no map iteration order — so the output is byte-stable
     * across machines and JDKs.
     */
    fun buildDraft(): ComposeStackDraft {
        val services = (0 until SERVICE_COUNT).map { index ->
            val name = serviceName(index)
            // Spread services across a few shapes so the file is not 400 copies of one block: the
            // highlighter, the virtualized list, and the parser all behave differently on varied
            // block lengths, and a uniform file would hide that.
            val role = ROLES[index % ROLES.size]
            val tier = index % 4
            ComposeServiceDraft(
                serviceName = name,
                image = "registry.example.test/omniterm/$role:1.${index % 12}.${index % 7}",
                containerName = "omniterm-large-$name",
                restart = RESTARTS[index % RESTARTS.size],
                command = "/usr/local/bin/omniterm-$role --index $index --tier $tier --workers ${2 + tier}",
                ports = (0..tier).map { p ->
                    "${18000 + index * 4 + p}:${8000 + p}"
                }.toMutableList(),
                environment = buildEnvironment(index, name, role, tier),
                volumes = mutableListOf(
                    "./data/$name/state:/var/lib/omniterm/$role",
                    "./data/$name/cache:/var/cache/omniterm",
                    "./config/$name.conf:/etc/omniterm/$role.conf:ro",
                ),
                networks = if (tier == 0) {
                    mutableListOf("omniterm-edge")
                } else {
                    mutableListOf("omniterm-edge", "omniterm-internal")
                },
                // Chain each service to the previous one so depends_on is exercised with real
                // targets that the parser can resolve, instead of dangling names.
                dependsOn = if (index == 0) mutableListOf() else mutableListOf(serviceName(index - 1)),
            )
        }
        return ComposeStackDraft(
            projectName = "omniterm-large-stack",
            stackName = "omniterm_large_stack",
            services = services.toMutableList(),
            topVolumes = mutableListOf(
                TopLevelVolumeDraft(name = "omniterm-shared-state"),
                TopLevelVolumeDraft(name = "omniterm-shared-cache"),
            ),
            topNetworks = mutableListOf(
                TopLevelNetworkDraft(name = "omniterm-edge", driver = "bridge"),
                TopLevelNetworkDraft(name = "omniterm-internal", driver = "bridge"),
            ),
        )
    }

    private fun buildEnvironment(index: Int, name: String, role: String, tier: Int): MutableList<String> =
        mutableListOf(
            "OMNITERM_SERVICE_NAME=$name",
            "OMNITERM_SERVICE_INDEX=$index",
            "OMNITERM_SERVICE_ROLE=$role",
            "OMNITERM_SERVICE_TIER=$tier",
            "OMNITERM_LOG_LEVEL=${LOG_LEVELS[index % LOG_LEVELS.size]}",
            "OMNITERM_UPSTREAM_URL=http://${serviceName((index + 1) % SERVICE_COUNT)}:8000/healthz",
            "OMNITERM_METRICS_PATH=/var/lib/omniterm/$role/metrics-$index.prom",
            "OMNITERM_FEATURE_FLAGS=tier-$tier,role-$role,batch-${index % 5}",
        )

    /** Render the committed fixture text. */
    fun render(): String = generateDockerComposeYaml(buildDraft())

    fun sha256(text: String): String =
        MessageDigest.getInstance("SHA-256")
            .digest(text.toByteArray(Charsets.UTF_8))
            .joinToString("") { "%02x".format(it) }

    /**
     * Resolve the committed fixture by locating the repository root and appending [REPO_PATH].
     * Gradle runs unit tests with the module directory as the working directory, but that is a
     * Gradle detail rather than a guarantee, so search upwards for a root marker instead of
     * hardcoding `../`. Anchoring on the root rather than on the fixture itself means this still
     * resolves when the file is absent, which is exactly the case regeneration has to handle.
     */
    fun repoFile(): File {
        var dir: File? = File(".").absoluteFile
        while (dir != null) {
            if (File(dir, "settings.gradle.kts").isFile) return File(dir, REPO_PATH)
            dir = dir.parentFile
        }
        error("Could not locate the repository root from ${File(".").absolutePath}")
    }

    private val ROLES = listOf("edge-proxy", "api-worker", "batch-runner", "cache-node", "log-shipper")
    private val RESTARTS = listOf("unless-stopped", "always", "on-failure")
    private val LOG_LEVELS = listOf("debug", "info", "warn", "error")
}
