#!/usr/bin/env bash
# Manage the disposable SSH fixtures in scripts/test-hosts/docker-compose.yml.
#
# A small fleet whose shape mirrors OmniTerm's connection surface (auth modes + every proxyType),
# reusable by any feature that needs a reachable Linux host -- not just one test.
#
# LOCAL DEVELOPER TOOL ONLY. Nothing in .github/workflows or scripts/local-pr-check.sh invokes
# this, and it must stay that way: hosted runners would need Docker-in-Docker, the containers pull
# images from the network mid-run, and required CI must not depend on external image registries.
# CI's instrumentation coverage is the emulator-based Room migration matrix, which needs no hosts.
#
#   ./scripts/test-hosts.sh up       # generate keys if needed, start, wait until SSH answers
#   ./scripts/test-hosts.sh down     # stop and remove (host keys and volumes discarded)
#   ./scripts/test-hosts.sh status   # container state and port mapping
#   ./scripts/test-hosts.sh verify   # prove every auth mode and proxy path actually works
#   ./scripts/test-hosts.sh keys     # print host fingerprints (compare against the app's dialog)
#   ./scripts/test-hosts.sh fleet    # print the settings to enter in OmniTerm
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/scripts/test-hosts"
COMPOSE_FILE="$DIR/docker-compose.yml"
KEY_DIR="$DIR/keys"
PLAIN_KEY="$KEY_DIR/omniterm_test_ed25519"
PASS_KEY="$KEY_DIR/omniterm_test_passphrase_ed25519"
ENV_FILE="$DIR/.env"

# Credentials are generated per machine into $ENV_FILE (gitignored), never committed. Hard-coding
# even a throwaway password in a public repo is a secret-scanning finding and an example others
# copy. Generated once, then reused so already-added hosts in the app keep working across restarts.
ensure_env() {
  if [ ! -f "$ENV_FILE" ]; then
    mkdir -p "$DIR"
    local old_umask; old_umask=$(umask); umask 077
    {
      echo "# Generated by scripts/test-hosts.sh -- local throwaway test fixtures, not secrets."
      echo "# Delete this file to rotate; you will then need to re-add the hosts in the app."
      echo "OMNITERM_TEST_USER=omniterm"
      echo "OMNITERM_TEST_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-24)"
      echo "OMNITERM_TEST_KEY_PASSPHRASE=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-24)"
    } >"$ENV_FILE"
    umask "$old_umask"
    echo "generated $ENV_FILE"
  fi
  # shellcheck disable=SC1090
  set -a; . "$ENV_FILE"; set +a
}
ensure_env

KEY_PASSPHRASE="$OMNITERM_TEST_KEY_PASSPHRASE"
USER_NAME="$OMNITERM_TEST_USER"
PASSWORD="$OMNITERM_TEST_PASSWORD"

# name:port:auth
EDGE_HOSTS=(
  "omniterm-test-direct:2201:password"
  "omniterm-test-keyauth:2202:key"
  "omniterm-test-keyauth-passphrase:2204:key-passphrase"
  "omniterm-test-bastion:2203:password"
)
PROXY_PORTS=(1080 8888)

compose() { docker compose -f "$COMPOSE_FILE" "$@"; }
ssh_opts=(-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10)

require_docker() {
  command -v docker >/dev/null || { echo "docker is required" >&2; exit 1; }
  docker info >/dev/null 2>&1 || { echo "cannot talk to the docker daemon" >&2; exit 1; }
}

ensure_keys() {
  mkdir -p "$KEY_DIR"
  [ -f "$PLAIN_KEY" ] || ssh-keygen -q -t ed25519 -N "" -C omniterm-test -f "$PLAIN_KEY"
  # Presence is not enough for the passphrase key: deleting .env rotates the passphrase, which
  # leaves an existing key unopenable and surfaces as a confusing auth failure rather than a
  # regeneration. Prove the current passphrase still opens it, and rebuild the pair if it does not.
  if [ -f "$PASS_KEY" ] && ! ssh-keygen -y -P "$KEY_PASSPHRASE" -f "$PASS_KEY" >/dev/null 2>&1; then
    echo "passphrase key no longer matches .env; regenerating" >&2
    rm -f "$PASS_KEY" "$PASS_KEY.pub"
  fi
  [ -f "$PASS_KEY" ] || ssh-keygen -q -t ed25519 -N "$KEY_PASSPHRASE" -C omniterm-test-passphrase -f "$PASS_KEY"
  chmod 600 "$PLAIN_KEY" "$PASS_KEY"
  chmod 644 "$PLAIN_KEY.pub" "$PASS_KEY.pub"
}

wait_for_port() {
  local port="$1" i
  for i in $(seq 1 60); do
    (echo >"/dev/tcp/127.0.0.1/$port") 2>/dev/null && return 0
    sleep 2
  done
  echo "timed out waiting for 127.0.0.1:$port" >&2
  return 1
}

# An open port is NOT readiness. The `direct` host installs packages via DOCKER_MODS before its
# user account exists, so sshd accepts connections while auth still fails -- which would surface
# later as a flaky test rather than a startup error. Wait for an actual successful login.
wait_for_auth() {
  local port="$1" i
  command -v sshpass >/dev/null || { sleep 20; return 0; }
  for i in $(seq 1 60); do
    if sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p "$port" "$USER_NAME@127.0.0.1" true 2>/dev/null; then
      return 0
    fi
    sleep 3
  done
  echo "timed out waiting for SSH auth on 127.0.0.1:$port" >&2
  return 1
}

case "${1:-}" in
  up)
    require_docker
    ensure_keys
    # Fail loudly on a port owned by something else -- this machine may also run a real homelab.
    for entry in "${EDGE_HOSTS[@]}"; do
      p="${entry#*:}"; p="${p%%:*}"
      if (echo >"/dev/tcp/127.0.0.1/$p") 2>/dev/null &&
         ! docker ps --format '{{.Ports}}' | grep -q ":$p->"; then
        echo "port $p is already in use by something that is not a test host" >&2
        exit 1
      fi
    done
    compose up -d
    for entry in "${EDGE_HOSTS[@]}"; do
      p="${entry#*:}"; p="${p%%:*}"
      wait_for_port "$p" || exit 1
    done
    for p in "${PROXY_PORTS[@]}"; do wait_for_port "$p" || exit 1; done
    # Password hosts gate readiness; the key hosts come up with the same image and no package mod.
    wait_for_auth 2201 || exit 1
    wait_for_auth 2203 || exit 1
    echo "test fleet ready. Run './scripts/test-hosts.sh fleet' for the settings to enter."
    ;;

  down)
    require_docker
    compose down -v --remove-orphans
    echo "test fleet removed"
    ;;

  status)
    require_docker
    docker ps -a --filter "name=omniterm-test" \
      --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
    ;;

  verify)
    require_docker
    command -v sshpass >/dev/null || { echo "sshpass is required for verify" >&2; exit 1; }
    ensure_keys
    rc=0
    check() { # label, then command
      local label="$1"; shift
      printf '%-46s ' "$label"
      if out=$("$@" 2>/dev/null) && [ -n "$out" ]; then echo "OK  ($out)"; else echo "FAILED"; rc=1; fi
    }

    check "password auth      direct   :2201" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2201 "$USER_NAME@127.0.0.1" 'uname -s'
    check "password auth      bastion  :2203" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2203 "$USER_NAME@127.0.0.1" 'uname -s'
    check "key auth           keyauth  :2202" \
      ssh "${ssh_opts[@]}" -i "$PLAIN_KEY" -o IdentitiesOnly=yes -p 2202 "$USER_NAME@127.0.0.1" 'uname -s'
    check "key+passphrase     keyauth  :2204" \
      sshpass -P assphrase -p "$KEY_PASSPHRASE" \
        ssh "${ssh_opts[@]}" -i "$PASS_KEY" -o IdentitiesOnly=yes -p 2204 "$USER_NAME@127.0.0.1" 'uname -s'
    # internal-a has no published port: reaching it at all proves the path under test.
    check "ssh jump           bastion -> internal-a" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2203 "$USER_NAME@127.0.0.1" \
        "sshpass -p $PASSWORD ssh ${ssh_opts[*]} omniterm@omniterm-test-internal-a hostname 2>/dev/null || getent hosts omniterm-test-internal-a"
    check "socks5 proxy       :1080 -> internal-a" \
      docker run --rm --network omniterm-test-internal alpine/socat -T3 - TCP:omniterm-test-internal-a:2222,connect-timeout=5
    check "http proxy reachable :8888" \
      bash -c 'exec 3<>/dev/tcp/127.0.0.1/8888 && echo reachable'
    check "socks5 proxy reachable :1080" \
      bash -c 'exec 3<>/dev/tcp/127.0.0.1/1080 && echo reachable'
    exit "$rc"
    ;;

  keys)
    require_docker
    for c in $(docker ps --filter "name=omniterm-test" --format '{{.Names}}' | sort); do
      [ "$c" = "omniterm-test-proxy" ] && continue
      printf '%-40s ' "$c"
      docker exec "$c" ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub 2>/dev/null | awk '{print $2}'
    done
    ;;

  fleet)
    cat <<EOF
Enter these in OmniTerm. From an Android emulator the host machine is 10.0.2.2
(use 127.0.0.1 when testing from this machine directly).

  direct              10.0.2.2:2201  user=$USER_NAME  password=$PASSWORD    proxy: none
  key auth            10.0.2.2:2202  user=$USER_NAME  key=$PLAIN_KEY        proxy: none
  key + passphrase    10.0.2.2:2204  user=$USER_NAME  key=$PASS_KEY         proxy: none
                                     passphrase=$KEY_PASSPHRASE
  bastion (jump)      10.0.2.2:2203  user=$USER_NAME  password=$PASSWORD    proxy: none

  internal-a          omniterm-test-internal-a:2222   user=$USER_NAME  password=$PASSWORD
      reachable ONLY via one of:
        proxy: ssh     jump  10.0.2.2:2203 ($USER_NAME/$PASSWORD)
        proxy: socks5  10.0.2.2:1080
        proxy: http    10.0.2.2:8888
EOF
    ;;

  *)
    sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
    exit 2
    ;;
esac
