#!/usr/bin/env bash
# Manage the disposable SSH fixtures in scripts/test-hosts/docker-compose.yml.
#
# A small fleet whose shape mirrors OmniTerm's connection surface (auth modes + every proxyType),
# reusable by any feature that needs a reachable Linux host -- not just one test.
#
# LOCAL DEVELOPER TOOL ONLY. Nothing in .github/workflows or scripts/local-pr-check.sh invokes
# this, and it must stay that way: hosted runners would need Docker-in-Docker, the containers pull
# images from the network mid-run, and required CI must not depend on external image registries.
# CI's instrumentation coverage is the emulator-based Room migration matrix, which needs no hosts.
#
#   ./scripts/test-hosts.sh up       # generate keys if needed, start, wait until SSH answers
#   ./scripts/test-hosts.sh down     # stop and remove (host keys and volumes discarded)
#   ./scripts/test-hosts.sh status   # container state and port mapping
#   ./scripts/test-hosts.sh verify   # prove every auth mode and proxy path actually works
#   ./scripts/test-hosts.sh keys     # print host fingerprints (compare against the app's dialog)
#   ./scripts/test-hosts.sh fleet    # print the settings to enter in OmniTerm
#   ./scripts/test-hosts.sh android [serial] # reverse the fixture ports to a physical device
#   ./scripts/test-hosts.sh android-clear [serial] # remove only those reverse mappings
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/scripts/test-hosts"
COMPOSE_FILE="$DIR/docker-compose.yml"
KEY_DIR="$DIR/keys"
PLAIN_KEY="$KEY_DIR/omniterm_test_ed25519"
PASS_KEY="$KEY_DIR/omniterm_test_passphrase_ed25519"
ENV_FILE="$DIR/.env"

# Credentials are generated per machine into $ENV_FILE (gitignored), never committed. Hard-coding
# even a throwaway password in a public repo is a secret-scanning finding and an example others
# copy. Generated once, then reused so already-added hosts in the app keep working across restarts.
ensure_env() {
  if [ ! -f "$ENV_FILE" ]; then
    mkdir -p "$DIR"
    local old_umask; old_umask=$(umask); umask 077
    {
      echo "# Generated by scripts/test-hosts.sh -- local throwaway test fixtures, not secrets."
      echo "# Delete this file to rotate; you will then need to re-add the hosts in the app."
      if [ -S /run/omniterm-test-docker.sock ]; then
        echo "OMNITERM_TEST_DOCKER_HOST=unix:///run/omniterm-test-docker.sock"
      fi
      echo "OMNITERM_TEST_USER=omniterm"
      echo "OMNITERM_TEST_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-24)"
      echo "OMNITERM_TEST_KEY_PASSPHRASE=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-24)"
    } >"$ENV_FILE"
    umask "$old_umask"
    echo "generated $ENV_FILE"
  fi
  # shellcheck disable=SC1090
  set -a; . "$ENV_FILE"; set +a
}
ensure_env

# Optional reusable engine context. Keep credentials and local daemon selection in the same
# gitignored file without baking either into the Compose model. A caller's explicit DOCKER_HOST
# remains authoritative.
if [ -z "${DOCKER_HOST:-}" ] && [ -n "${OMNITERM_TEST_DOCKER_HOST:-}" ]; then
  export DOCKER_HOST="$OMNITERM_TEST_DOCKER_HOST"
fi

KEY_PASSPHRASE="$OMNITERM_TEST_KEY_PASSPHRASE"
USER_NAME="$OMNITERM_TEST_USER"
PASSWORD="$OMNITERM_TEST_PASSWORD"

# name:port:auth
EDGE_HOSTS=(
  "omniterm-test-direct:2201:password"
  "omniterm-test-keyauth:2202:key"
  "omniterm-test-keyauth-passphrase:2204:key-passphrase"
  "omniterm-test-runtime-docker:2205:password"
  "omniterm-test-runtime-podman:2206:password"
  "omniterm-test-bastion:2203:password"
)
PROXY_PORTS=(1080 8888)
SHARE_PORTS=(21 445 8082)
ANDROID_PORTS=(21 445 1080 2201 2202 2203 2204 2205 2206 8080 8081 8082 8888)

compose() { docker compose -f "$COMPOSE_FILE" "$@"; }
ssh_opts=(-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10)

require_docker() {
  command -v docker >/dev/null || { echo "docker is required" >&2; exit 1; }
  docker info >/dev/null 2>&1 || { echo "cannot talk to the docker daemon" >&2; exit 1; }
}

ensure_keys() {
  mkdir -p "$KEY_DIR"
  [ -f "$PLAIN_KEY" ] || ssh-keygen -q -t ed25519 -N "" -C omniterm-test -f "$PLAIN_KEY"
  # Presence is not enough for the passphrase key: deleting .env rotates the passphrase, which
  # leaves an existing key unopenable and surfaces as a confusing auth failure rather than a
  # regeneration. Prove the current passphrase still opens it, and rebuild the pair if it does not.
  if [ -f "$PASS_KEY" ] && ! ssh-keygen -y -P "$KEY_PASSPHRASE" -f "$PASS_KEY" >/dev/null 2>&1; then
    echo "passphrase key no longer matches .env; regenerating" >&2
    rm -f "$PASS_KEY" "$PASS_KEY.pub"
  fi
  [ -f "$PASS_KEY" ] || ssh-keygen -q -t ed25519 -N "$KEY_PASSPHRASE" -C omniterm-test-passphrase -f "$PASS_KEY"
  chmod 600 "$PLAIN_KEY" "$PASS_KEY"
  chmod 644 "$PLAIN_KEY.pub" "$PASS_KEY.pub"
}

wait_for_port() {
  local port="$1" i
  for i in $(seq 1 60); do
    (echo >"/dev/tcp/127.0.0.1/$port") 2>/dev/null && return 0
    sleep 2
  done
  echo "timed out waiting for 127.0.0.1:$port" >&2
  return 1
}

# An open port is NOT readiness. The `direct` host installs packages via DOCKER_MODS before its
# user account exists, so sshd accepts connections while auth still fails -- which would surface
# later as a flaky test rather than a startup error. Wait for an actual successful login.
wait_for_auth() {
  local port="$1" i
  command -v sshpass >/dev/null || { sleep 20; return 0; }
  for i in $(seq 1 60); do
    if sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p "$port" "$USER_NAME@127.0.0.1" true 2>/dev/null; then
      return 0
    fi
    sleep 3
  done
  echo "timed out waiting for SSH auth on 127.0.0.1:$port" >&2
  return 1
}

case "${1:-}" in
  up)
    require_docker
    ensure_keys
    # Fail loudly on a port owned by something else -- this machine may also run a real homelab.
    for entry in "${EDGE_HOSTS[@]}"; do
      p="${entry#*:}"; p="${p%%:*}"
      if (echo >"/dev/tcp/127.0.0.1/$p") 2>/dev/null &&
         ! docker ps --format '{{.Ports}}' | grep -q ":$p->"; then
        echo "port $p is already in use by something that is not a test host" >&2
        exit 1
      fi
    done
    compose up -d
    for entry in "${EDGE_HOSTS[@]}"; do
      p="${entry#*:}"; p="${p%%:*}"
      wait_for_port "$p" || exit 1
    done
    for p in "${PROXY_PORTS[@]}"; do wait_for_port "$p" || exit 1; done
    for p in "${SHARE_PORTS[@]}"; do wait_for_port "$p" || exit 1; done
    # Password hosts gate readiness; the key hosts come up with the same image and no package mod.
    wait_for_auth 2201 || exit 1
    wait_for_auth 2203 || exit 1
    wait_for_auth 2205 || exit 1
    wait_for_auth 2206 || exit 1
    echo "test fleet ready. Run './scripts/test-hosts.sh fleet' for the settings to enter."
    ;;

  down)
    require_docker
    compose down -v --remove-orphans
    echo "test fleet removed"
    ;;

  status)
    require_docker
    docker ps -a --filter "name=omniterm-test" \
      --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
    ;;

  verify)
    require_docker
    command -v sshpass >/dev/null || { echo "sshpass is required for verify" >&2; exit 1; }
    ensure_keys
    rc=0
    tmp_dir="$(mktemp -d)"
    trap 'rm -rf "$tmp_dir"' EXIT
    check() { # label, then command
      local label="$1"; shift
      printf '%-46s ' "$label"
      if out=$("$@" 2>/dev/null) && [ -n "$out" ]; then echo "OK  ($out)"; else echo "FAILED"; rc=1; fi
    }

    # Write probes. Each echoes the bytes it read back, so `check`'s non-empty rule is what proves
    # the round trip; a silent failure anywhere in the chain prints FAILED.
    probe_name() { printf 'verify-write-%s-%s.txt' "$1" "$$"; }

    smb_write_probe() {
      local name; name=$(probe_name smb)
      docker exec omniterm-test-shares sh -c "
        set -e
        printf 'smb-write-probe\n' >/tmp/$name
        smbclient //127.0.0.1/fixture -U '$USER_NAME%$PASSWORD' \
          -c 'put /tmp/$name $name' >/dev/null
        smbclient //127.0.0.1/fixture -U '$USER_NAME%$PASSWORD' -c 'get $name -'
        smbclient //127.0.0.1/fixture -U '$USER_NAME%$PASSWORD' -c 'rm $name' >/dev/null
      "
    }

    ftp_write_probe() {
      local name; name=$(probe_name ftp)
      printf 'ftp-write-probe\n' >"$tmp_dir/$name"
      curl --silent --show-error --fail --user "$USER_NAME:$PASSWORD" \
        -T "$tmp_dir/$name" "ftp://127.0.0.1/$name" >/dev/null || return 1
      curl --silent --show-error --fail --user "$USER_NAME:$PASSWORD" \
        "ftp://127.0.0.1/$name" || return 1
      curl --silent --show-error --fail --user "$USER_NAME:$PASSWORD" \
        -Q "-DELE $name" "ftp://127.0.0.1/" >/dev/null
    }

    webdav_write_probe() {
      local name; name=$(probe_name webdav)
      local base=http://127.0.0.1:8082/fixture
      printf 'webdav-write-probe\n' >"$tmp_dir/$name"
      curl --silent --show-error --fail --user "$USER_NAME:$PASSWORD" \
        -T "$tmp_dir/$name" "$base/$name" >/dev/null || return 1
      curl --silent --show-error --fail --user "$USER_NAME:$PASSWORD" "$base/$name" || return 1
      curl --silent --show-error --fail --user "$USER_NAME:$PASSWORD" \
        -X DELETE "$base/$name" >/dev/null
    }

    check "password auth      direct   :2201" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2201 "$USER_NAME@127.0.0.1" 'uname -s'
    check "password auth      bastion  :2203" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2203 "$USER_NAME@127.0.0.1" 'uname -s'
    check "key auth           keyauth  :2202" \
      ssh "${ssh_opts[@]}" -i "$PLAIN_KEY" -o IdentitiesOnly=yes -p 2202 "$USER_NAME@127.0.0.1" 'uname -s'
    check "key+passphrase     keyauth  :2204" \
      sshpass -P assphrase -p "$KEY_PASSPHRASE" \
        ssh "${ssh_opts[@]}" -i "$PASS_KEY" -o IdentitiesOnly=yes -p 2204 "$USER_NAME@127.0.0.1" 'uname -s'
    # internal-a has no published port: reaching it at all proves the path under test.
    check "ssh jump           bastion -> internal-a" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2203 "$USER_NAME@127.0.0.1" \
        "sshpass -p $PASSWORD ssh ${ssh_opts[*]} omniterm@omniterm-test-internal-a hostname 2>/dev/null || getent hosts omniterm-test-internal-a"
    check "socks5 proxy       :1080 -> internal-a" \
      docker run --rm --network omniterm-test-internal alpine/socat -T3 - TCP:omniterm-test-internal-a:2222,connect-timeout=5
    check "http proxy reachable :8888" \
      bash -c 'exec 3<>/dev/tcp/127.0.0.1/8888 && echo reachable'
    check "socks5 proxy reachable :1080" \
      bash -c 'exec 3<>/dev/tcp/127.0.0.1/1080 && echo reachable'
    check "SMB auth + read      :445/fixture" \
      docker exec omniterm-test-shares smbclient //127.0.0.1/fixture \
        -U "$USER_NAME%$PASSWORD" -c 'get fixture.txt -'
    check "FTP auth + read      :21" \
      curl --silent --show-error --fail --user "$USER_NAME:$PASSWORD" \
        ftp://127.0.0.1/fixture.txt
    check "WebDAV auth + list   :8082/fixture" \
      curl --silent --show-error --fail --user "$USER_NAME:$PASSWORD" \
        -X PROPFIND -H 'Depth: 1' -o /dev/null -w '%{http_code}' \
        http://127.0.0.1:8082/fixture/
    # Reads alone are not enough. Every share protocol passed `verify` for weeks while WebDAV PUT
    # returned 500 on the device, because nothing here ever wrote. Each probe writes a uniquely
    # named file, reads the same bytes back and removes it, leaving the seeded baseline untouched.
    check "SMB write round trip  :445/fixture" smb_write_probe
    check "FTP write round trip  :21" ftp_write_probe
    check "WebDAV write round trip :8082/fixture" webdav_write_probe
    check "isolated Docker host :2205" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2205 "$USER_NAME@127.0.0.1" \
        'docker info --format "{{.ServerVersion}} {{.Driver}}"'
    check "isolated Podman host :2206" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2206 "$USER_NAME@127.0.0.1" \
        'podman info --format "{{.Version.Version}} {{.Store.GraphDriverName}}"'
    check "Docker Compose smoke :2205" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2205 "$USER_NAME@127.0.0.1" \
        'set -e; cd "$HOME/omniterm-e2e/runtime"; trap "docker compose -p omniterm-e2e-docker down -v >/dev/null 2>&1 || true" EXIT; docker compose -p omniterm-e2e-docker up -d >/dev/null; docker compose -p omniterm-e2e-docker ps --services --status running'
    check "Podman Compose smoke :2206" \
      sshpass -p "$PASSWORD" ssh "${ssh_opts[@]}" -p 2206 "$USER_NAME@127.0.0.1" \
        'set -e; cd "$HOME/omniterm-e2e/runtime"; trap "podman-compose -p omniterm-e2e-podman down -v >/dev/null 2>&1 || true" EXIT; podman-compose -p omniterm-e2e-podman up -d >/dev/null; podman ps --filter label=com.jetsetslow.omniterm.fixture=runtime-smoke --format "{{.Names}}"'
    exit "$rc"
    ;;

  keys)
    require_docker
    for c in $(docker ps --filter "name=omniterm-test" --format '{{.Names}}' | sort); do
      [ "$c" = "omniterm-test-proxy" ] && continue
      printf '%-40s ' "$c"
      docker exec "$c" ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub 2>/dev/null | awk '{print $2}'
    done
    ;;

  fleet)
    cat <<EOF
Enter these in OmniTerm. From an Android emulator the host machine is 10.0.2.2
(use 127.0.0.1 when testing from this machine directly). For a physical device, first run
\`./scripts/test-hosts.sh android <serial>\` and use 127.0.0.1 for every address below.

  direct              10.0.2.2:2201  user=$USER_NAME  password=$PASSWORD    proxy: none
  key auth            10.0.2.2:2202  user=$USER_NAME  key=$PLAIN_KEY        proxy: none
  key + passphrase    10.0.2.2:2204  user=$USER_NAME  key=$PASS_KEY         proxy: none
                                     passphrase=$KEY_PASSPHRASE
  bastion (jump)      10.0.2.2:2203  user=$USER_NAME  password=$PASSWORD    proxy: none
  Docker runtime      10.0.2.2:2205  user=$USER_NAME  password=$PASSWORD    isolated DinD
  Podman runtime      10.0.2.2:2206  user=$USER_NAME  password=$PASSWORD    isolated rootful

  internal-a          omniterm-test-internal-a:2222   user=$USER_NAME  password=$PASSWORD
      reachable ONLY via one of:
        proxy: ssh     jump  10.0.2.2:2203 ($USER_NAME/$PASSWORD)
        proxy: socks5  10.0.2.2:1080
        proxy: http    10.0.2.2:8888

Also served, for the Network Tools and tunnel suites (see fixtures/lab-http/nginx.conf):

  http origin         10.0.2.2:8080, :8081     also 127.0.0.1:8080 ON the direct host itself,
                                               which is what -L and -D tunnels dial
  SMB share           10.0.2.2:445   share=fixture  user=$USER_NAME  password=$PASSWORD
  FTP share           10.0.2.2:21    path=/         user=$USER_NAME  password=$PASSWORD
  WebDAV share        10.0.2.2:8082  path=fixture   user=$USER_NAME  password=$PASSWORD  HTTP

The share volume starts with fixture.txt and nested/hello.txt, stays writable across \`up\` calls,
and is discarded only by \`down\`.

Fixture files mounted read-only into direct:

  /fixtures/large-stack/compose.yml            400-service stack for the Compose builder stress test

The runtime hosts copy the writable Compose fixtures to:

  /home/$USER_NAME/omniterm-e2e/runtime         Docker + Podman smoke and custom-build stacks
  /home/$USER_NAME/omniterm-e2e/corpus          committed Compose parser corpus
  /home/$USER_NAME/omniterm-e2e/large-stack.yml committed 400-service builder fixture
EOF
    ;;

  android|android-clear)
    command -v adb >/dev/null || { echo "adb is required" >&2; exit 1; }
    serial="${2:-}"
    if [ -z "$serial" ]; then
      mapfile -t devices < <(adb devices | awk 'NR > 1 && $2 == "device" && $1 !~ /^emulator-/ { print $1 }')
      [ "${#devices[@]}" -eq 1 ] || {
        echo "pass a physical device serial (found ${#devices[@]})" >&2
        exit 1
      }
      serial="${devices[0]}"
    fi
    for p in "${ANDROID_PORTS[@]}" $(seq 21100 21110); do
      if [ "$1" = android ]; then
        adb -s "$serial" reverse "tcp:$p" "tcp:$p" >/dev/null
      else
        adb -s "$serial" reverse --remove "tcp:$p" >/dev/null 2>&1 || true
      fi
    done
    if [ "$1" = android ]; then
      echo "fixture ports reversed to $serial; use 127.0.0.1 in OmniTerm"
      adb -s "$serial" reverse --list
    else
      echo "fixture reverse mappings removed from $serial"
    fi
    ;;

  *)
    sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
    exit 2
    ;;
esac
